using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace TestNetworkApp.Smoke
{
    internal static partial class SmokeTests
    {
        public static IReadOnlyDictionary<string, Func<CancellationToken, Task<SmokeTestResult>>> GetImplementedTests()
            => new Dictionary<string, Func<CancellationToken, Task<SmokeTestResult>>>(StringComparer.OrdinalIgnoreCase)
            {
                ["INFRA-001"] = Infra_WinDivertDriver,
                ["INFRA-002"] = Infra_FilterRegistration,
                ["INFRA-003"] = Infra_FilterOrder,
                ["INFRA-004"] = Infra_AdminRights,
                ["INFRA-005"] = Infra_EncodingCp866,
                ["INFRA-006"] = Infra_FilterListMutationDuringProcessing_DoesNotThrow,
                ["INFRA-007"] = Infra_ConcurrentFilterChurnAndProcessing_DoesNotThrow,
                ["INFRA-008"] = Infra_RapidApplyDisableDuringProcessing_DoesNotThrow,

                ["UI-001"] = Ui_OrchestratorInitialized_InViewModel,
                ["UI-002"] = Ui_StartStopCommand_CallsCancelBranch_NoGui,
                ["UI-003"] = Ui_RelayCommand_DoesNotSwallowExceptions,
                ["UI-004"] = Ui_BypassToggle_UpdatesTlsServiceOptions,
                ["UI-005"] = Ui_BypassPreset_SaveDoesNotOverwriteTtlOrRedirect,
                ["UI-006"] = Ui_BypassMetrics_UpdatesFromService,
                ["UI-007"] = Ui_Verdict_ChangesBrushByColor,
                ["UI-008"] = Ui_TestResultsManager_AddsCardToObservableCollection,
                ["UI-009"] = Ui_TestResultsManager_UpdatesExistingCard_NoDuplicates,
                ["UI-010"] = Ui_ParsePipelineMessage_ParsesUiLines,
                ["UI-011"] = Ui_UiReducerSmoke,
                ["UI-012"] = Ui_SniHostname_HasPriorityOverIp_InCardKey,
                ["UI-013"] = Ui_NetworkChangePrompt_ShowsAndHides_NoGui,

                ["ORCH-001"] = Orch_Pipeline_StartStop_ViaRetestTargets,
                ["ORCH-002"] = Orch_MonitoringServices_StartStop_AdminGated,
                ["ORCH-003"] = Orch_SniGating_ByPid_AllowsOnlyTracked,
                ["ORCH-004"] = Orch_EarlySniBuffered_ThenFlushed_OnPidAppear,
                ["ORCH-005"] = Orch_ProcessExit_StopsMonitoring,
                ["ORCH-006"] = Orch_PidTracker_AddRemovePid,
                ["ORCH-007"] = Orch_PidTracker_IsPidTracked,

                ["ERR-001"] = Err_DnsFailure_DoesNotCrash,
                ["ERR-002"] = Err_VpnDetected_WarningIsConsistent,
                ["ERR-003"] = Err_WinDivertMissing_FallbackPollingStarts,
                ["ERR-004"] = Err_TrafficEngine_HandleCleanup_AdminGated,
                ["ERR-005"] = Err_FilterException_DoesNotCrashEngine_AdminGated,
                ["ERR-006"] = Err_DoHOnly_NoHostname_DoesNotCrash,
                ["ERR-007"] = Err_Ipv6Host_ParsesAndTests,
                ["ERR-008"] = Err_LongClientHello_Fragmentation_NoOverflow,

                ["E2E-001"] = E2E_FullPipeline_EnqueueToUiCard,
                ["E2E-002"] = E2E_BypassEnabled_ProducesFragmentationMetrics,
                ["E2E-003"] = E2E_AutoBypass_PreemptivePreset_AppliesExpectedOptions,
                ["E2E-004"] = E2E_AttachProcess_AddPid_AllowsTraffic,
                ["E2E-005"] = E2E_ProcessExit_StopsMonitoring,

                ["PERF-001"] = PERF_Load_500Hosts_HealthLogAndNoBacklog,
                ["PERF-002"] = PERF_Memory_NoLinearGrowth_ShortRun,
                ["PERF-003"] = PERF_Store_ThreadSafety_InMemoryBlockageStateStore,

                ["REG-001"] = REG_Tracert_Cp866_NoMojibake,
                ["REG-002"] = REG_VpnWarning_WhenVpnDetected,
                ["REG-003"] = REG_ApplyTransactions_Persisted_RoundTrip_NoWpf,
                ["REG-004"] = REG_PerCardRetest_Queued_DuringRun_ThenFlushed,
                ["REG-005"] = REG_QuicFallback_Selective_MultiTarget_DoesNotForgetPrevious,
                ["REG-006"] = REG_Tcp443TlsStrategy_PerTarget_MultiGroup,
                ["REG-007"] = REG_Tcp80HttpHostTricks_PerTarget_MultiGroup,
                ["REG-008"] = REG_CapabilitiesUnion_TlsFragmentAndDisorder_StayEnabled,
                ["REG-009"] = REG_ApplyTransactions_ContractV2_HasRequestSnapshotResultContributions,
                ["REG-010"] = REG_ApplyTransactions_ResultStatus_Applied_IsPersisted,
                ["REG-011"] = REG_ApplyTransactions_ResultStatus_AndRollback_ArePersisted,
                ["REG-012"] = REG_ApplyV2Plan_IsSerialized_NoParallelApply,
                ["REG-013"] = REG_GroupBypassAttachmentStore_DeterministicMerge_AndExcludedSticky,
                ["REG-014"] = REG_GroupParticipation_Persisted_RoundTrip_ThroughStore,
                ["REG-015"] = REG_ObservedIps_Seeded_FromCandidateEndpoints,

                ["PIPE-005"] = Pipe_UnifiedFilter_LoopbackDropped,
                ["PIPE-006"] = Pipe_UnifiedFilter_NoiseOnlyOnDisplay,
                ["PIPE-001"] = Pipe_ConnectionMonitor_PublishesEvents_OnTcpConnect,
                ["PIPE-002"] = Pipe_TrafficCollector_PidFiltering_IgnoresOtherPid,
                ["PIPE-003"] = Pipe_DnsParser_SniParsing_OneShotAndFragmented,
                ["PIPE-004"] = Pipe_Orchestrator_SniGating_ByRemoteEndpointPid,
                ["PIPE-007"] = Pipe_StateStore_Dedup_SingleSession,
                ["PIPE-008"] = Pipe_Tester_DnsResolve_Google,
                ["PIPE-009"] = Pipe_Tester_TcpHandshake_Google443,
                ["PIPE-010"] = Pipe_Tester_TlsHandshake_Google443_Sni,
                ["PIPE-011"] = Pipe_Tester_ReverseDns_8888,
                ["PIPE-017"] = Pipe_PipelineHealth_EmitsLog_OnActivity,
                ["PIPE-018"] = Pipe_AutoHostlist_AppendedToV2Tail,
                ["PIPE-019"] = Pipe_AutoHostlist_V2Only_NoLegacyTypes,
                ["PIPE-012"] = Pipe_Classifier_DnsBlocked,
                ["PIPE-013"] = Pipe_Classifier_TcpTimeout,
                ["PIPE-014"] = Pipe_Classifier_TcpReset,
                ["PIPE-015"] = Pipe_Classifier_DpiFilter_Tls,
                ["PIPE-016"] = Pipe_Classifier_FakeIpRange,

                ["INSP-001"] = Insp_RstInspection_TtlInjectionDetected,
                ["INSP-002"] = Insp_RstInspection_IpIdAnomalyDetected,
                ["INSP-003"] = Insp_UdpInspection_QuicBlockageDetected,
                ["INSP-004"] = Insp_TcpRetransmissionTracker_DropSuspicion,
                ["INSP-005"] = Insp_HttpRedirectDetector_BlockpageHost,

                ["DPI2-001"] = Dpi2_SignalsAdapter_Observe_AdaptsLegacySignals_ToTtlStore,
                ["DPI2-002"] = Dpi2_SignalStore_Ttl_DeletesEventsOlderThan10Minutes,
                ["DPI2-003"] = Dpi2_Aggregation_BuildSnapshot_RespectsWindow_30s_60s,
                ["DPI2-016"] = Dpi2_Aggregation_BuildSnapshot_ExtractsRstTtlDelta_AndLatency,
                ["DPI2-031"] = Dpi2_Aggregation_BuildSnapshot_ExtractsRstIpIdDelta_AndSuspiciousCount,
                ["DPI2-004"] = Dpi2_DiagnosisEngine_ProducesDiagnosis_WithConfidenceAtLeast50,
                ["DPI2-017"] = Dpi2_DiagnosisEngine_RstTtlDelta_FastClassifiesAsActiveDpiEdge,
                ["DPI2-018"] = Dpi2_DiagnosisEngine_RstTtlDelta_SlowClassifiesAsStatefulDpi,
                ["DPI2-032"] = Dpi2_DiagnosisEngine_SingleRstAnomaly_IsUnknown_NotDpi,
                ["DPI2-005"] = Dpi2_DiagnosisEngine_Explanation_IsFactBased_NoStrategiesMentioned,
                ["DPI2-006"] = Dpi2_GateMarkers_Gate1_EmittedInProgressLog,
                ["DPI2-007"] = Dpi2_StrategySelector_BuildsPlan_AndExecutorFormatsRecommendation,
                ["DPI2-008"] = Dpi2_StrategySelector_HighRiskBlocked_WhenConfidenceBelow70,
                ["DPI2-009"] = Dpi2_StrategySelector_EmptyPlan_WhenConfidenceBelow50,
                ["DPI2-034"] = Dpi2_StrategySelector_DnsHijack_RecommendsUseDohOnly,
                ["DPI2-010"] = Dpi2_StrategySelector_WarnsAndSkips_UnimplementedStrategies,
                ["DPI2-033"] = Dpi2_StrategySelector_Phase3Strategies_AreImplemented,
                ["DPI2-014"] = Dpi2_StrategySelector_Feedback_AffectsOrdering_WhenEnoughSamples,
                ["DPI2-015"] = Dpi2_StrategySelector_Feedback_DoesNotAffect_WhenNotEnoughSamples,
                ["DPI2-011"] = Dpi2_ExecutorMvp_FormatsCompactOutput_OneLine,
                ["DPI2-012"] = Dpi2_AllV2Outputs_StartWithPrefix,
                ["DPI2-013"] = Dpi2_ExecutorMvp_DoesNotCallTrafficEngineOrBypassController,
                ["DPI2-025"] = Dpi2_Guard_NoLegacySignalsOrGetSignals_InV2RuntimePath,
                ["DPI2-026"] = Dpi2_Guard_BypassStateManager_IsSingleSourceOfTruth,
                ["DPI2-027"] = Dpi2_Watchdog_CrashRecovery_AndTimeout_DisablesBypass,
                ["DPI2-028"] = Dpi2_ActivationDetection_Statuses_AreDeterministic,
                ["DPI2-029"] = Dpi2_OutcomeCheck_Https_TaggedProbe_IsDeterministic_ViaTaggedProbe,
                ["DPI2-030"] = Dpi2_QuicFallback_DropUdp443_IsSelectiveByObservedIp,
                ["DPI2-040"] = Dpi2_PolicySetCompiler_DetectsHardConflicts,
                ["DPI2-041"] = Dpi2_PolicyDrivenUdp443_DropUdp443_ViaDecisionGraph,
                ["DPI2-042"] = Dpi2_PolicyDrivenTtlEndpointBlock_Expires_AndHasHigherPriority,
                ["DPI2-043"] = Dpi2_PolicyDrivenTcp80_HttpHostTricks_ViaDecisionGraph,
                ["DPI2-044"] = Dpi2_PolicyDrivenTcp443_TlsStrategySelection_ViaDecisionGraph,
                ["DPI2-045"] = Dpi2_SemanticGroups_Statuses_AreDeterministic,
                ["DPI2-046"] = Dpi2_PolicySnapshotExport_AndActivePolicies_AreValid,
                ["DPI2-047"] = Dpi2_PerTargetPolicy_UsesCandidateEndpointsSeed_NoDnsRequired,
                    ["DPI2-048"] = Dpi2_PerTargetTcp80Policy_UsesCandidateEndpointsSeed_NoDnsRequired,
                ["DPI2-019"] = Dpi2_ExecutorV2_ManualApply_MapsPlanToBypassOptions,
                ["DPI2-020"] = Dpi2_ExecutorV2_Cancel_RollbacksToPreviousState,
                ["DPI2-021"] = Dpi2_Pipeline_DoesNotAutoApply_BypassControllerOrTlsBypassService,
                ["DPI2-022"] = Dpi2_ExecutorV2_TlsFragment_Params_AffectPresetAndAutoAdjust,
                ["DPI2-023"] = Dpi2_StrategySelector_PopulatesTlsFragmentParameters,
                ["DPI2-024"] = Dpi2_E2E_SelectorPlan_ManualApply_UsesPlanParams,

                ["CFG-001"] = Cfg_BypassProfile_Load,
                ["CFG-002"] = Cfg_BypassProfile_SaveChanges,
                ["CFG-003"] = Cfg_BypassProfile_CorruptJson_Graceful,
                ["CFG-004"] = Cfg_NoiseHostFilter_Singleton,
                ["CFG-005"] = Cfg_NoiseHostFilter_LoadAndMatch,

                ["BYPASS-001"] = Bypass_TlsBypassService_RegistersFilter,
                ["BYPASS-002"] = Bypass_TlsBypassService_RemovesFilter,
                ["BYPASS-003"] = Bypass_TlsBypassService_MetricsUpdated_Periodic,
                ["BYPASS-004"] = Bypass_TlsBypassService_VerdictChanged_RatioThresholds,
                ["BYPASS-005"] = Bypass_TlsBypassService_ProfilePresetPresent,
                ["BYPASS-006"] = Bypass_BypassFilter_Fragments_ClientHello_SeqAndLen,
                ["BYPASS-007"] = Bypass_BypassFilter_Disorder_ReversesSegments,
                ["BYPASS-008"] = Bypass_BypassFilter_TtlTrick_SendsFakeLowTtl,
                ["BYPASS-009"] = Bypass_BypassFilter_DropRst_DropsInboundRst,
                ["BYPASS-010"] = Bypass_BypassFilter_Gating_443AndSni,
                ["BYPASS-011"] = Bypass_BypassFilter_Threshold_ShortClientHelloNotFragmented,
                ["BYPASS-012"] = Bypass_BypassFilter_TtlTrick_ManualEnabled_WithFragmentation,
                ["BYPASS-013"] = Bypass_TlsBypassService_AutoTtl_SelectsAndPersistsBest,
                ["BYPASS-014"] = Bypass_TlsBypassService_AutoAdjustAggressive_EarlyRst_ShrinksMinChunkTo4,
                ["BYPASS-015"] = Bypass_TlsBypassService_AutoAdjustAggressive_GreenOver30s_RelaxesMinChunk,
                ["BYPASS-016"] = Bypass_BypassFilter_HttpHostTricks_SplitsHostHeader,
                ["BYPASS-017"] = Bypass_BypassFilter_BadChecksum_UsesSendExWithoutRecalc,
            };

        public static Task<SmokeTestResult> NotImplemented(string id, string name, CancellationToken ct)
            => Task.FromResult(new SmokeTestResult(
                id,
                string.IsNullOrWhiteSpace(name) ? "Не реализовано" : name,
                SmokeOutcome.Fail,
                TimeSpan.Zero,
                "Тест из плана присутствует, но ещё не реализован в SmokeRunner"));
    }
}
